import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, map } from 'rxjs';
import { environment } from '../environments/environment';
import { Account, Attendance, DashboardStats, Member, Membership, Trainer, Workout } from './models';

interface ApiResponse<T> { success: boolean; data: T; message?: string; id?: number; }

@Injectable({ providedIn: 'root' })
export class ApiService {
  private readonly http = inject(HttpClient);
  readonly baseUrl = environment.apiUrl;
  getMembers(): Observable<Member[]> { return this.http.get<ApiResponse<Record<string, unknown>[]>>(`${this.baseUrl}/members`).pipe(map(response => response.data.map(row => this.member(row)))); }
  getAccounts(): Observable<Account[]> { return this.http.get<ApiResponse<Account[]>>(`${this.baseUrl}/users`).pipe(map(response => response.data)); }
  getAdminMembers(): Observable<any[]> { return this.http.get<ApiResponse<any[]>>(`${this.baseUrl}/admin/members`).pipe(map(response => response.data)); }
  getAdminTrainers(): Observable<any[]> { return this.http.get<ApiResponse<any[]>>(`${this.baseUrl}/admin/trainers`).pipe(map(response => response.data)); }
  getAdminPrograms(): Observable<any[]> { return this.http.get<ApiResponse<any[]>>(`${this.baseUrl}/admin/programs`).pipe(map(response => response.data)); }
  getAdminAttendance(): Observable<any[]> { return this.http.get<ApiResponse<any[]>>(`${this.baseUrl}/admin/attendance`).pipe(map(response => response.data)); }
  setAccountStatus(id: number, isActive: boolean): Observable<void> { return this.http.patch<void>(`${this.baseUrl}/users/${id}/status`, { isActive }); }
  getMember(id: number): Observable<Member> { return this.http.get<ApiResponse<Record<string, unknown>>>(`${this.baseUrl}/members/${id}`).pipe(map(response => this.member(response.data))); }
  createMember(payload: Record<string, unknown>): Observable<number> { return this.http.post<ApiResponse<unknown>>(`${this.baseUrl}/members`, payload).pipe(map(response => response.id as number)); }
  updateMember(id: number, payload: Record<string, unknown>): Observable<void> { return this.http.put<void>(`${this.baseUrl}/members/${id}`, payload); }
  getProfile(): Observable<Record<string, unknown>> { return this.http.get<ApiResponse<Record<string, unknown>>>(`${this.baseUrl}/profile`).pipe(map(response => response.data)); }
  updateProfile(payload: Record<string, unknown>): Observable<void> { return this.http.put<void>(`${this.baseUrl}/profile`, payload); }
  deleteMember(id: number): Observable<void> { return this.http.delete<void>(`${this.baseUrl}/members/${id}`); }
  getTrainers(): Observable<Trainer[]> { return this.http.get<ApiResponse<Record<string, unknown>[]>>(`${this.baseUrl}/trainers`).pipe(map(response => response.data.map(row => this.trainer(row)))); }
  createTrainer(payload: Record<string, unknown>): Observable<number> { return this.http.post<ApiResponse<unknown>>(`${this.baseUrl}/trainers`, payload).pipe(map(response => response.id as number)); }
  updateTrainer(id: number, payload: Record<string, unknown>): Observable<void> { return this.http.put<void>(`${this.baseUrl}/trainers/${id}`, payload); }
  deleteTrainer(id: number): Observable<void> { return this.http.delete<void>(`${this.baseUrl}/trainers/${id}`); }
  getMemberships(): Observable<Membership[]> { return this.http.get<ApiResponse<Record<string, unknown>[]>>(`${this.baseUrl}/memberships`).pipe(map(response => response.data.map(row => this.membership(row)))); }
  createMembership(payload: Record<string, unknown>): Observable<number> { return this.http.post<ApiResponse<unknown>>(`${this.baseUrl}/memberships`, payload).pipe(map(response => response.id as number)); }
  updateMembership(id: number, payload: Record<string, unknown>): Observable<void> { return this.http.put<void>(`${this.baseUrl}/memberships/${id}`, payload); }
  deleteMembership(id: number): Observable<void> { return this.http.delete<void>(`${this.baseUrl}/memberships/${id}`); }
  getWorkouts(): Observable<Workout[]> { return this.http.get<ApiResponse<Record<string, unknown>[]>>(`${this.baseUrl}/workouts`).pipe(map(response => response.data.map(row => this.workout(row)))); }
  createWorkout(payload: Record<string, unknown>): Observable<number> { return this.http.post<ApiResponse<unknown>>(`${this.baseUrl}/workouts`, payload).pipe(map(response => response.id as number)); }
  updateWorkout(id: number, payload: Record<string, unknown>): Observable<void> { return this.http.put<void>(`${this.baseUrl}/workouts/${id}`, payload); }
  deleteWorkout(id: number): Observable<void> { return this.http.delete<void>(`${this.baseUrl}/workouts/${id}`); }
  getPrograms(): Observable<Workout[]> { return this.http.get<ApiResponse<Record<string, unknown>[]>>(`${this.baseUrl}/programs`).pipe(map(response => response.data.map(row => this.workout(row)))); }
  enrollProgram(programId: number): Observable<void> { return this.http.post<void>(`${this.baseUrl}/program-enroll`, { programId }); }
  getSelectedTrainer(): Observable<Trainer | null> { return this.http.get<ApiResponse<Record<string, unknown> | null>>(`${this.baseUrl}/member-trainer`).pipe(map(response => response.data ? this.trainer(response.data) : null)); }
  chooseTrainer(trainerId: number): Observable<void> { return this.http.post<void>(`${this.baseUrl}/member-trainer`, { trainerId }); }
  getMemberTrainers(): Observable<Trainer[]> { return this.http.get<ApiResponse<Record<string, unknown>[]>>(`${this.baseUrl}/trainers-for-members`).pipe(map(response => response.data.map(row => this.trainer(row)))); }
  getTrainerMembers(): Observable<any[]> { return this.http.get<ApiResponse<any[]>>(`${this.baseUrl}/trainer-members`).pipe(map(response => response.data.map(row => ({ ...row, name: `${row.first_name} ${row.last_name}`, fitnessGoal: row.fitness_goal, assignedAt: row.assigned_at ? new Date(row.assigned_at).toLocaleDateString() : '', enrollmentCount: Number(row.enrollment_count || 0), active: Boolean(row.is_active) })))); }
  getMyPrograms(): Observable<Workout[]> { return this.http.get<ApiResponse<Record<string, unknown>[]>>(`${this.baseUrl}/my-programs`).pipe(map(response => response.data.map(row => this.workout(row)))); }
  getTrainerPrograms(): Observable<Workout[]> { return this.http.get<ApiResponse<Record<string, unknown>[]>>(`${this.baseUrl}/trainer/programs`).pipe(map(response => response.data.map(row => this.workout(row)))); }
  updateTrainerProgram(enrollmentId: number, payload: Record<string, unknown>): Observable<void> { return this.http.patch<void>(`${this.baseUrl}/trainer/programs/${enrollmentId}`, payload); }
  getAttendance(): Observable<Attendance[]> { return this.http.get<ApiResponse<Record<string, unknown>[]>>(`${this.baseUrl}/attendance`).pipe(map(response => response.data.map(row => this.attendance(row)))); }
  recordAttendance(payload: Record<string, unknown>): Observable<number> { return this.http.post<ApiResponse<unknown>>(`${this.baseUrl}/attendance`, payload).pipe(map(response => response.id as number)); }
  updateAttendance(id: number, payload: Record<string, unknown>): Observable<void> { return this.http.put<void>(`${this.baseUrl}/attendance/${id}`, payload); }
  deleteAttendance(id: number): Observable<void> { return this.http.delete<void>(`${this.baseUrl}/attendance/${id}`); }
  getDashboardStats(): Observable<DashboardStats> { return this.http.get<ApiResponse<Record<string, unknown>>>(`${this.baseUrl}/dashboard/stats`).pipe(map(response => this.dashboard(response.data))); }
  private dashboard(row: Record<string, unknown>): DashboardStats { const membership = row['currentMembership'] as Record<string, unknown> | null | undefined; const trainer = row['currentTrainer'] as Record<string, unknown> | null | undefined; const recent = Array.isArray(row['recentAttendance']) ? row['recentAttendance'] as Record<string, unknown>[] : []; const upcoming = Array.isArray(row['upcomingWorkouts']) ? row['upcomingWorkouts'] as Record<string, unknown>[] : []; return { totalUsers: Number(row['totalUsers'] ?? 0), totalMembers: Number(row['totalMembers'] ?? 0), activeMembers: Number(row['activeMembers'] ?? 0), totalTrainers: Number(row['totalTrainers'] ?? 0), totalPrograms: Number(row['totalPrograms'] ?? 0), activeMemberships: Number(row['activeMemberships'] ?? 0), todayAttendance: Number(row['todayAttendance'] ?? 0), assignedWorkouts: Number(row['assignedWorkouts'] ?? 0), activeEnrollments: Number(row['activeEnrollments'] ?? 0), managedMembers: Number(row['managedMembers'] ?? 0), attendanceCount: Number(row['attendanceCount'] ?? 0), fitnessGoal: row['fitnessGoal'] ? String(row['fitnessGoal']) : null, currentMembership: membership ? this.membership(membership) : null, currentTrainer: trainer ? this.trainer(trainer) : null, recentAttendance: recent.map(item => this.attendance(item)), upcomingWorkouts: upcoming.map(item => this.workout(item)) }; }
  private member(row: Record<string, unknown>): Member { const firstName = String(row['first_name'] ?? ''); const lastName = String(row['last_name'] ?? ''); return { id: Number(row['id']), userId: Number(row['user_id']), name: `${firstName} ${lastName}`.trim(), firstName, lastName, email: String(row['email'] ?? ''), phone: String(row['phone'] ?? ''), plan: String(row['membership_name'] ?? 'No plan'), status: row['is_active'] ? 'Active' : 'Expired', joined: this.date(row['created_at']), avatar: `${firstName[0] ?? ''}${lastName[0] ?? ''}` }; }
  private trainer(row: Record<string, unknown>): Trainer { const first = String(row['first_name'] ?? ''); const last = String(row['last_name'] ?? ''); return { id: Number(row['trainer_id'] ?? row['id']), name: `${first} ${last}`.trim(), specialty: String(row['specialization'] ?? 'General fitness'), bio: String(row['bio'] ?? ''), yearsOfExperience: Number(row['years_of_experience'] ?? 0), certifications: String(row['certifications'] ?? ''), members: 0, rating: 0, status: 'Available' }; }
  private membership(row: Record<string, unknown>): Membership { return { id: Number(row['id']), memberId: Number(row['member_id']), name: String(row['name']), price: Number(row['price'] ?? 0), period: 'month', members: 1, description: `${row['first_name'] ?? ''} ${row['last_name'] ?? ''}`.trim(), accent: 'mint', startDate: String(row['start_date'] ?? ''), endDate: String(row['end_date'] ?? ''), status: String(row['status'] ?? '') }; }
  private workout(row: Record<string, unknown>): Workout { const first = String(row['trainer_first_name'] ?? ''); const last = String(row['trainer_last_name'] ?? ''); const memberFirst = String(row['first_name'] ?? ''); const memberLast = String(row['last_name'] ?? ''); return { id: Number(row['id'] ?? row['workout_id']), memberId: row['member_id'] == null ? undefined : Number(row['member_id']), trainerId: Number(row['trainer_id'] ?? 0), name: String(row['title']), category: 'Training plan', duration: 0, level: String(row['adjusted_difficulty'] ?? row['frequency'] ?? 'Custom'), calories: 0, trainer: `${first} ${last}`.trim() || 'Unassigned', memberName: `${memberFirst} ${memberLast}`.trim() || undefined, description: String(row['description'] ?? ''), goals: String(row['goals'] ?? ''), frequency: String(row['frequency'] ?? ''), enrolled: Boolean(row['enrolled']), enrollment_status: row['enrollment_status'] ? String(row['enrollment_status']) : undefined, enrollmentId: row['enrollment_id'] == null ? undefined : Number(row['enrollment_id']), adjustedDuration: row['adjusted_duration'] == null ? undefined : String(row['adjusted_duration']), adjustedDifficulty: row['adjusted_difficulty'] == null ? undefined : String(row['adjusted_difficulty']), trainerNotes: row['trainer_notes'] == null ? undefined : String(row['trainer_notes']) }; }
  private attendance(row: Record<string, unknown>): Attendance { const first = String(row['first_name'] ?? ''); const last = String(row['last_name'] ?? ''); return { id: Number(row['id']), memberId: Number(row['member_id']), member: `${first} ${last}`.trim(), date: String(row['attendance_date'] ?? ''), time: String(row['check_in'] ?? row['check_out'] ?? ''), type: row['check_out'] ? 'Check-out' : 'Check-in', status: String(row['status'] ?? '') }; }
  private date(value: unknown): string { return value ? new Date(String(value)).toLocaleDateString() : ''; }
}
