import { Routes } from '@angular/router';
import { authGuard } from './auth.guard';
import { AppShellComponent, RoleDashboardComponent, AdminDashboardComponent, TrainerDashboardComponent, MemberDashboardComponent, LandingComponent, LoginComponent, RegisterComponent, MembersComponent, MemberDetailComponent, TrainersComponent, MembershipsComponent, WorkoutsComponent, AttendanceComponent, ProfileComponent } from './pages-http';
import { AccountsComponent, FindTrainerComponent, ProgramsComponent, MyProgramsComponent, TrainerMembersComponent } from './pages-workflows';
export const routes: Routes = [
  { path: '', component: LandingComponent }, { path: 'login', component: LoginComponent }, { path: 'register', component: RegisterComponent },
  { path: '', component: AppShellComponent, canActivate: [authGuard], children: [
    { path: 'accounts', component: AccountsComponent, canActivate: [authGuard], data: { roles: ['admin'] } }, { path: 'find-trainer', component: FindTrainerComponent, canActivate: [authGuard], data: { roles: ['member'] } }, { path: 'programs', component: ProgramsComponent, canActivate: [authGuard], data: { roles: ['admin', 'member'] } }, { path: 'my-programs', component: MyProgramsComponent, canActivate: [authGuard], data: { roles: ['member'] } }, { path: 'trainer-members', component: TrainerMembersComponent, canActivate: [authGuard], data: { roles: ['trainer'] } },
    { path: 'dashboard', component: RoleDashboardComponent, canActivate: [authGuard] }, { path: 'dashboard/admin', component: AdminDashboardComponent, canActivate: [authGuard], data: { roles: ['admin'] } }, { path: 'dashboard/trainer', component: TrainerDashboardComponent, canActivate: [authGuard], data: { roles: ['trainer'] } }, { path: 'dashboard/member', component: MemberDashboardComponent, canActivate: [authGuard], data: { roles: ['member'] } }, { path: 'members', component: MembersComponent, canActivate: [authGuard], data: { roles: ['admin', 'trainer'] } }, { path: 'members/:id', component: MemberDetailComponent, canActivate: [authGuard], data: { roles: ['admin', 'trainer'] } }, { path: 'trainers', component: TrainersComponent, canActivate: [authGuard], data: { roles: ['admin'] } }, { path: 'memberships', component: MembershipsComponent, canActivate: [authGuard], data: { roles: ['admin', 'member'] } }, { path: 'workouts', component: WorkoutsComponent, canActivate: [authGuard], data: { roles: ['admin'] } }, { path: 'attendance', component: AttendanceComponent, canActivate: [authGuard], data: { roles: ['admin', 'trainer', 'member'] } }, { path: 'profile', component: ProfileComponent, canActivate: [authGuard], data: { roles: ['trainer', 'member'] } }, { path: '', pathMatch: 'full', redirectTo: 'dashboard' }
  ] }, { path: '**', redirectTo: '' }
];
