export type UserRole = 'admin' | 'trainer' | 'member';
export interface AuthUser { id: number; email: string; firstName: string; lastName: string; role: UserRole; phone?: string; gender?: string; }
export interface Account { id: number; first_name: string; last_name: string; email: string; phone?: string; role: UserRole; is_active: boolean; created_at: string; }
export interface Member { id: number; userId?: number; name: string; firstName?: string; lastName?: string; email: string; phone: string; plan: string; status: 'Active' | 'Paused' | 'Expired'; joined: string; avatar: string; }
export interface Trainer { id: number; name: string; specialty: string; members: number; rating: number; status: 'Available' | 'In session'; bio?: string; yearsOfExperience?: number; certifications?: string; }
export interface Membership { id: number; memberId: number; name: string; price: number; period: string; members: number; description: string; accent: string; startDate: string; endDate: string; status: string; }
export interface Workout { id: number; memberId?: number; trainerId?: number; name: string; category: string; duration: number; level: string; calories: number; trainer: string; memberName?: string; description?: string; goals?: string; frequency?: string; enrolled?: boolean; enrollment_status?: string; enrollmentId?: number; adjustedDuration?: string; adjustedDifficulty?: string; trainerNotes?: string; }
export interface Attendance { id?: number; memberId: number; date: string; member: string; time: string; type: 'Check-in' | 'Check-out'; status?: string; trainerName?: string; }
export interface DashboardStats { members?: number; trainers?: number; activeMemberships?: number; todayAttendance: number; activeMembers?: number; totalUsers?: number; totalMembers?: number; totalTrainers?: number; totalPrograms?: number; assignedWorkouts?: number; activeEnrollments?: number; managedMembers?: number; attendanceCount?: number; currentMembership?: Membership | null; currentTrainer?: Trainer | null; fitnessGoal?: string | null; recentAttendance?: Attendance[]; upcomingWorkouts?: Workout[]; }
