import { NgFor, NgIf } from '@angular/common';
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService } from './api.service';
import { AuthService } from './auth.service';
import { Account, Trainer, Workout } from './models';

const errorText = (error: any) => error?.error?.message || 'Request failed. Please try again.';

@Component({ standalone: true, imports: [NgFor, NgIf], template: `<div class="page-heading"><h1>Users</h1></div><p class="error" *ngIf="error">{{error}}</p><p *ngIf="loading">Loading users...</p><section class="panel"><table *ngIf="accounts.length"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Created</th><th>Action</th></tr></thead><tbody><tr *ngFor="let account of accounts"><td>{{account.first_name}} {{account.last_name}}</td><td>{{account.email}}</td><td>{{account.role}}</td><td>{{account.is_active ? 'Active' : 'Inactive'}}</td><td>{{account.created_at}}</td><td><button *ngIf="account.role !== 'admin'" (click)="toggle(account)">{{account.is_active ? 'Deactivate' : 'Activate'}}</button></td></tr></tbody></table><p *ngIf="!loading&&!accounts.length">No users available.</p></section>` })
export class AccountsComponent { private readonly api = inject(ApiService); accounts: Account[] = []; loading = true; error = ''; constructor() { this.load(); } load(): void { this.api.getAccounts().subscribe({ next: value => { this.accounts = value; this.loading = false; }, error: error => { this.error = errorText(error); this.loading = false; } }); } toggle(account: Account): void { this.api.setAccountStatus(account.id, !account.is_active).subscribe({ next: () => this.load(), error: error => this.error = errorText(error) }); } }

@Component({ standalone: true, imports: [NgFor, NgIf], template: `<div class="page-heading"><h1>Find Your Trainer</h1></div><p class="success" *ngIf="message">{{message}}</p><p class="error" *ngIf="error">{{error}}</p><p *ngIf="loading">Loading trainers...</p><section class="panel"><p *ngIf="selected">Current trainer: <strong>{{selected.name}}</strong></p><p *ngIf="!selected&&!loading">No trainer selected yet.</p><article class="trainer-card" *ngFor="let trainer of trainers"><h2>{{trainer.name}}</h2><p>{{trainer.specialty}}</p><p>{{trainer.bio || 'Bio not provided.'}}</p><p>{{trainer.yearsOfExperience}} years experience<span *ngIf="trainer.certifications"> · {{trainer.certifications}}</span></p><button (click)="choose(trainer)" [disabled]="selected?.id === trainer.id">{{selected?.id === trainer.id ? 'Selected' : 'Choose Trainer'}}</button></article><p *ngIf="!loading&&!trainers.length">No trainers available.</p></section>` })
export class FindTrainerComponent { private readonly api = inject(ApiService); trainers: Trainer[] = []; selected: Trainer | null = null; loading = true; error = ''; message = ''; constructor() { this.api.getMemberTrainers().subscribe({ next: value => { this.trainers = value; this.loading = false; }, error: error => { this.error = errorText(error); this.loading = false; } }); this.api.getSelectedTrainer().subscribe({ next: value => this.selected = value, error: error => this.error = errorText(error) }); } choose(trainer: Trainer): void { this.api.chooseTrainer(trainer.id).subscribe({ next: () => { this.selected = trainer; this.message = 'Trainer selected successfully.'; }, error: error => this.error = errorText(error) }); } }

@Component({ standalone: true, imports: [NgFor, NgIf], template: `<div class="page-heading"><h1>My Members</h1></div><p class="error" *ngIf="error">{{error}}</p><p *ngIf="loading">Loading members...</p><section class="panel"><table *ngIf="members.length"><thead><tr><th>Member</th><th>Email</th><th>Fitness goal</th><th>Assigned</th><th>Programs</th><th>Status</th></tr></thead><tbody><tr *ngFor="let member of members"><td>{{member.name}}</td><td>{{member.email}}</td><td>{{member.fitnessGoal || 'Not set'}}</td><td>{{member.assignedAt || 'Unknown'}}</td><td>{{member.enrollmentCount}}</td><td>{{member.active ? 'Active' : 'Inactive'}}</td></tr></tbody></table><p *ngIf="!loading&&!members.length">No members assigned yet.</p></section>` })
export class TrainerMembersComponent { private readonly api = inject(ApiService); members: any[] = []; loading = true; error = ''; constructor() { this.api.getTrainerMembers().subscribe({ next: value => { this.members = value; this.loading = false; }, error: error => { this.error = errorText(error); this.loading = false; } }); } }

@Component({ standalone: true, imports: [NgFor, NgIf, FormsModule], template: `<div class="page-heading"><h1>Programs</h1><button *ngIf="auth.role()==='admin'" (click)="beginCreate()">{{editing ? 'Cancel' : 'Add Program'}}</button></div><p class="success" *ngIf="message">{{message}}</p><p class="error" *ngIf="error">{{error}}</p><form class="panel" *ngIf="editing" (ngSubmit)="save()"><input [(ngModel)]="draft.title" name="title" placeholder="Program name" required><textarea [(ngModel)]="draft.description" name="description" placeholder="Description"></textarea><input [(ngModel)]="draft.goals" name="goals" placeholder="Goal"><input [(ngModel)]="draft.frequency" name="frequency" placeholder="Duration / difficulty"><button type="submit">{{draft.id ? 'Save changes' : 'Create program'}}</button></form><p *ngIf="loading">Loading programs...</p><section class="panel"><article class="workout-row" *ngFor="let program of programs"><strong>{{program.name || program.title}}</strong><span>{{program.goals || 'General fitness'}}</span><span>{{program.frequency || 'Duration not set'}}</span><span>{{program.description}}</span><span *ngIf="auth.role()==='admin'">Enrollments: {{program.enrollment_count || 0}}</span><button *ngIf="auth.role()==='admin'" (click)="beginEdit(program)">Edit</button><button *ngIf="auth.role()==='admin'" (click)="remove(program)">Delete</button><button *ngIf="auth.role()==='member'" (click)="enroll(program)" [disabled]="program.enrolled">{{program.enrolled ? 'Enrolled' : 'Enroll'}}</button></article><p *ngIf="!loading&&!programs.length">No workout programs available yet.</p></section>` })
export class ProgramsComponent { private readonly api = inject(ApiService); readonly auth = inject(AuthService); programs: any[] = []; loading = true; error = ''; message = ''; editing = false; draft: any = { title: '', description: '', goals: '', frequency: '' }; constructor() { this.load(); } load(): void { if (this.auth.role() === 'admin') { this.api.getAdminPrograms().subscribe({ next: value => { this.programs = value; this.loading = false; }, error: error => { this.error = errorText(error); this.loading = false; } }); } else { this.api.getPrograms().subscribe({ next: value => { this.programs = value; this.loading = false; }, error: error => { this.error = errorText(error); this.loading = false; } }); } } beginCreate(): void { this.editing = !this.editing; this.draft = { title: '', description: '', goals: '', frequency: '' }; } beginEdit(program: Workout): void { this.editing = true; this.draft = { id: program.id, title: program.name || (program as any).title, description: program.description || '', goals: program.goals || '', frequency: program.frequency || '' }; } save(): void { const id = this.draft.id; if (id) { this.api.updateWorkout(id, this.draft).subscribe({ next: () => this.saved('Program updated.'), error: error => this.error = errorText(error) }); } else { this.api.createWorkout(this.draft).subscribe({ next: () => this.saved('Program created.'), error: error => this.error = errorText(error) }); } } saved(message: string): void { this.editing = false; this.message = message; this.load(); } remove(program: Workout): void { if (!confirm(`Delete ${program.name || (program as any).title}?`)) return; this.api.deleteWorkout(program.id).subscribe({ next: () => { this.message = 'Program deleted.'; this.load(); }, error: error => this.error = errorText(error) }); } enroll(program: Workout): void { this.api.enrollProgram(program.id).subscribe({ next: () => { program.enrolled = true; this.message = 'You are enrolled in this program.'; }, error: error => this.error = errorText(error) }); } }

@Component({ standalone: true, imports: [NgFor, NgIf], template: `<div class="page-heading"><h1>My Programs</h1></div><p class="error" *ngIf="error">{{error}}</p><p *ngIf="loading">Loading enrolled programs...</p><section class="panel"><article class="workout-row" *ngFor="let program of programs"><strong>{{program.name}}</strong><span>{{program.description}}</span><span>{{program.goals}}</span><span>Duration: {{program.adjustedDuration || program.frequency}}</span><span>Difficulty: {{program.adjustedDifficulty || 'Not adjusted'}}</span><span>{{program.trainerNotes || 'No trainer notes'}}</span><span>{{program.enrollment_status}}</span></article><p *ngIf="!loading&&!programs.length">No programs enrolled yet.</p></section>` })
export class MyProgramsComponent { private readonly api = inject(ApiService); programs: Workout[] = []; loading = true; error = ''; constructor() { this.api.getMyPrograms().subscribe({ next: value => { this.programs = value; this.loading = false; }, error: error => { this.error = errorText(error); this.loading = false; } }); } }